name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, r: release}
          - {os: ubuntu-latest, r: oldrel-1}
          - {os: macos-latest, r: release}
          - {os: windows-latest, r: release}
    steps:
      - uses: actions/checkout@v5
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
      - name: Run tests
        run: Rscript tests/testthat.R
